package abs

import (
	"context"
	"testing"

	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity"
	"github.com/stretchr/testify/assert"
)

type mockDefenderForStorageClient struct {
	Enabled bool
	Error   error
}

func (mock *mockDefenderForStorageClient) Get(context.Context, string, armsecurity.SettingName, *armsecurity.DefenderForStorageClientGetOptions) (armsecurity.DefenderForStorageClientGetResponse, error) {
	return armsecurity.DefenderForStorageClientGetResponse{
		DefenderForStorageSetting: armsecurity.DefenderForStorageSetting{
			Properties: &armsecurity.DefenderForStorageSettingProperties{
				IsEnabled: &mock.Enabled,
			},
		},
	}, mock.Error
}

func Test_CCC_C07_TR01_T01_succeeds(t *testing.T) {
	// Arrange
	myMock := mockDefenderForStorageClient{
		Enabled: true,
		Error:   nil,
	}

	defenderForStorageClient = &myMock

	// Act
	result := CCC_C07_TR01_T01()

	// Assert
	assert.Equal(t, true, result.Passed)
	assert.Equal(t, "Microsoft Defender for Cloud is enabled for Azure Storage, this will scan for unusual access patterns and alert if any are found.", result.Message)
}

func Test_CCC_C07_TR01_T01_fails_when_get_errors(t *testing.T) {
	// Arrange
	myMock := mockDefenderForStorageClient{
		Enabled: true,
		Error:   assert.AnError,
	}

	defenderForStorageClient = &myMock

	// Act
	result := CCC_C07_TR01_T01()

	// Assert
	assert.Equal(t, false, result.Passed)
	assert.Equal(t, "Error getting Defender for Storage settings: assert.AnError general error for testing. Microsoft Defender for Cloud is not enabled for Azure Storage, therefore will not be scanning and alerting on unusual access patterns.", result.Message)
}

func Test_CCC_C07_TR01_T01_fails_when_disabled(t *testing.T) {
	// Arrange
	myMock := mockDefenderForStorageClient{
		Enabled: false,
		Error:   nil,
	}

	defenderForStorageClient = &myMock

	// Act
	result := CCC_C07_TR01_T01()

	// Assert
	assert.Equal(t, false, result.Passed)
	assert.Equal(t, "Microsoft Defender for Cloud is not enabled for Azure Storage, therefore will not be scanning and alerting on unusual access patterns.", result.Message)
}

func Test_CCC_C07_TR02_T01_succeeds(t *testing.T) {
	// Arrange
	myMock := mockDefenderForStorageClient{
		Enabled: true,
		Error:   nil,
	}

	defenderForStorageClient = &myMock

	// Act
	result := CCC_C07_TR02_T01()

	// Assert
	assert.Equal(t, true, result.Passed)
	assert.Equal(t, "Security alerts will be generated by Microsoft Defender for Cloud and are accessible for review via the Azure Security Center.", result.Message)
}

func Test_CCC_C07_TR02_T01_fails_when_disabled(t *testing.T) {
	// Arrange
	myMock := mockDefenderForStorageClient{
		Enabled: false,
		Error:   nil,
	}

	defenderForStorageClient = &myMock

	// Act
	result := CCC_C07_TR02_T01()

	// Assert
	assert.Equal(t, false, result.Passed)
	assert.Equal(t, "Microsoft Defender for Cloud is not enabled for Azure Storage, therefore security alerts will not be generated for this resource.", result.Message)
}
