package abs

import (
	"context"

	"github.com/privateerproj/privateer-sdk/pluginkit"
	"github.com/privateerproj/privateer-sdk/utils"

	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity"
)

// -----
// TestSet and Tests for CCC_C07_TR01
// -----

func CCC_C07_TR01() (testSetName string, result pluginkit.TestSetResult) {
	testSetName = "CCC_C07_TR01"
	result = pluginkit.TestSetResult{
		Passed:      false,
		Description: "When suspicious enumeration activities are detected, the service MUST generate real-time alerts to notify security personnel.",
		Message:     "TestSet has not yet started.",
		DocsURL:     "https://maintainer.com/docs/raids/ABS",
		ControlID:   "CCC.C07",
		Tests:       make(map[string]pluginkit.TestResult),
	}

	result.ExecuteTest(CCC_C07_TR01_T01)

	return
}

func CCC_C07_TR01_T01() (result pluginkit.TestResult) {
	result = pluginkit.TestResult{
		Description: "Confirms that Microsoft Defender for Cloud is enabled and alerting is enabled for Azure Storage, which will scan for and alert on unusual access inspection and unusual data exploration.",
		Function:    utils.CallerPath(0),
	}

	ConfirmDefenderForStorageIsEnabled(&result)

	if result.Passed {
		result.Message = "Microsoft Defender for Cloud is enabled for Azure Storage, this will scan for unusual access patterns and alert if any are found."
	} else {
		SetResultFailure(&result, "Microsoft Defender for Cloud is not enabled for Azure Storage, therefore will not be scanning and alerting on unusual access patterns.")
	}

	return
}

// -----
// TestSet and Tests for CCC_C07_TR02
// -----

func CCC_C07_TR02() (testSetName string, result pluginkit.TestSetResult) {
	testSetName = "CCC_C07_TR02"
	result = pluginkit.TestSetResult{
		Passed:      false,
		Description: "When suspicious enumeration activities are detected, the service MUST log the event, including the source details, time, and nature of the activity.",
		Message:     "TestSet has not yet started.",
		DocsURL:     "https://maintainer.com/docs/raids/ABS",
		ControlID:   "CCC.C07",
		Tests:       make(map[string]pluginkit.TestResult),
	}

	result.ExecuteTest(CCC_C07_TR02_T01)

	return
}

func CCC_C07_TR02_T01() (result pluginkit.TestResult) {
	result = pluginkit.TestResult{
		Description: "Confirms that security alerts around non-human enumerations attempts are being generated and are accessible for review.",
		Function:    utils.CallerPath(0),
	}

	ConfirmDefenderForStorageIsEnabled(&result)

	if result.Passed {
		result.Message = "Security alerts will be generated by Microsoft Defender for Cloud and are accessible for review via the Azure Security Center."
	} else {
		SetResultFailure(&result, "Microsoft Defender for Cloud is not enabled for Azure Storage, therefore security alerts will not be generated for this resource.")
	}
	return
}

// --------------------------------------
// Utility functions to support tests
// --------------------------------------

func ConfirmDefenderForStorageIsEnabled(result *pluginkit.TestResult) {
	defenderForStorageResponse, err := defenderForStorageClient.Get(context.Background(), storageAccountResourceId, armsecurity.SettingNameCurrent, &armsecurity.DefenderForStorageClientGetOptions{})

	if err != nil {
		SetResultFailure(result, "Error getting Defender for Storage settings: "+err.Error())
		return
	}

	if *defenderForStorageResponse.Properties.IsEnabled {
		result.Passed = true
	} else {
		result.Passed = false
	}
}
